Smoczek Portal/webapp/Controllers/BrokerController.cs
using AutoMapper;
using CloudCentre.DAL.Models;
using CloudCentre.Filters;
using CloudCentre.Models.ViewModels;
using CloudCentre.Services.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CloudCentre.Controllers
{
    [CurrentUserActionFilter]
    public class BrokerController : BaseController
    {
        private readonly IBrokerService _brokerService;
        public BrokerController(IBrokerService brokerService)
        {
            this._brokerService = brokerService;
        }

        [HttpGet]
        public ActionResult Brokers()
        {
            List<BrokerViewModel> viewModel = Mapper.Map<List<BrokerViewModel>>(_brokerService.GetBrokers());
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult CreateBroker()
        {
           BrokerViewModel viewModel = new BrokerViewModel() { Contract = _brokerService.RetriveLastContranctNumber() };
           return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBroker(BrokerViewModel viewModel)
        {
            if (!ModelState.IsValid) {
                return View(viewModel);
            }

            if (_brokerService.CheckIfContractNumberisTaken(viewModel.Contract))
            {
                ModelState.AddModelError("", "Ten numer umowy jest już zajety");
                return View(viewModel);
            }


            Broker broker = Mapper.Map<Broker>(viewModel);
            bool result = _brokerService.CreateBroker(broker);

            if (!result)
            {
                ModelState.AddModelError("", "Wystąpił błąd przy dodawaniu komisanta - sprawdż logi");
                return View(viewModel);
            }
            TempData["message"] = "Dodano komisanta";
            return RedirectToAction("Brokers");
        }


        [HttpGet]
        public ActionResult EditBroker(int Id)
        {
            if (Id == 0)
            {
                return RedirectToAction("Brokers");
            }

            Broker broker = _brokerService.GetBroker(Id);
            if (broker == null)
            {
                TempData["Error"] = "Nie ma takiego komisanta";
                return RedirectToAction("Brokers");
            }

            BrokerViewModel viewModel = Mapper.Map<BrokerViewModel>(broker);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBroker(BrokerViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            Broker broker = _brokerService.GetBroker(viewModel.ID);

            if(broker == null)
            {
                TempData["Error"] = "Nie ma takiego komisanta";
                return RedirectToAction("Brokers");
            }

            if (_brokerService.CheckIfContractNumberisTaken(viewModel.Contract))
            {
                if (broker.ID != viewModel.ID)
                {
                    ModelState.AddModelError("", "Ten numer umowy jest już zajety");
                    return View(viewModel);
                }
            }


            Mapper.Map(viewModel, broker);

            bool result = _brokerService.EditBroker(broker);

            if (!result)
            {
                ModelState.AddModelError("", "Wystąpił błąd przy edytowaniu komisanta - sprawdż logi");
                return View(viewModel);
            }
            TempData["message"] = "Dane Komisanta zstały zdytowane pomyślnie";
            return RedirectToAction("Brokers");
        }

        [HttpGet]
        public ActionResult ConfirmDeleteBroker(int Id)
        {
            Broker broker = _brokerService.GetBroker(Id);
            if (broker == null)
            {
                TempData["Error"] = "Nie ma takiego komisanta";
                return RedirectToAction("Brokers");
            }

            BrokerViewModel viewModel = Mapper.Map<BrokerViewModel>(broker);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmDeleteBroker(BrokerViewModel viewModel)
        {
            Broker broker = _brokerService.GetBroker(viewModel.ID);

            if (broker == null)
            {
                TempData["Error"] = "Nie ma takiego komisanta";
                return RedirectToAction("Brokers");
            }

            bool result = _brokerService.DeleteBroker(broker);

            if (!result)
            {
                ModelState.Clear();
                ModelState.AddModelError("", "Wystąpił błąd przy usuwaniu komisanta - sprawdż logi");
                return View(viewModel);
            }
            TempData["message"] = "Komisant został usuniety pomyślnie";
            return RedirectToAction("Brokers");
        }

       
    }
}

Smoczek Portal/webapp/Controllers/MessagesController.cs
using AutoMapper;
using CloudCentre.Infrastructure.Sms;
using CloudCentre.Models.ViewModels;
using CloudCentre.Services.Abstract;
using Hangfire;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CloudCentre.Controllers
{
    public class MessagesController : BaseController
    {
        private readonly IBrokerService _brokerService;
        private readonly IBackgroundJobClient _hangFireService;


        public MessagesController(IBrokerService brokerService, IBackgroundJobClient hangFireService)
        {
            this._brokerService = brokerService;
            this._hangFireService = hangFireService;
        }

        [HttpGet]
        public ActionResult SmsMessages()
        {
            var list = Mapper.Map<List<BrokerViewModel>>(_brokerService.GetBrokers().Where(x=>x.Phone!= null));
            SmsViewModel viewModel = new SmsViewModel();
            viewModel.BrokerSelect = new SelectList(list, "ID", "FullName");
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SmsMessages(SmsViewModel viewModel)
        {
            if(viewModel.BrokersIds != null && viewModel.BrokersIds.Length > 0) {
                foreach (var item in viewModel.BrokersIds)
                {
                    var broker = _brokerService.GetBroker(item);
                    _hangFireService.Enqueue<SmsProvider>(x => x.Send(broker.Phone.ToString(), viewModel.Message));
                }    
            }
            TempData["message"] = "Wysłano Sms-y";
            return RedirectToAction("Brokers", "Broker");
            }
        }
    }

Smoczek Portal/webapp/Controllers/ReportsController.cs
#region Using

using CloudCentre.Controllers;
using CloudCentre.DAL.Models;
using CloudCentre.Filters;
using CloudCentre.Models.ViewModels;
using CloudCentre.Services.Abstract;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

#endregion

namespace CloudCentrePortal.Controllers
{
    [CurrentUserActionFilter]
    [Broker]
    public class ReportsController : BaseController
    {
        private readonly IProductService _productService;
        private readonly IBrokerService _brokerService;


        public ReportsController(IProductService productService, IBrokerService brokerService)
        {
            this._productService = productService;
            this._brokerService = brokerService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ShowReport(ReportViewModel viewModel)
        {
           var productList =  _productService.GetProducts().Where(x => x.BrokerID == viewModel.BrookerId).Select(y => y.ID).ToArray();
            ReportViewModel reportViewModel = new ReportViewModel();
            reportViewModel.SoldProducts = _productService.GetSoldProducts().Where(x => productList.Contains(x.ProductID)).ToList();

            Broker broker = _brokerService.GetBroker(viewModel.BrookerId);

            if(broker == null)
            {
                TempData["Error"] = "Nie ma takiego komisanta";
                return RedirectToAction("Index", " Reports");
            }
            reportViewModel.FullName = string.Join(" ", broker.FirstName, broker.LastName);
            reportViewModel.ConctractNumber = broker.Contract.ToString();
            foreach ( var item in reportViewModel.SoldProducts)
            {
                reportViewModel.TotalValue += item.SoldPrice * item.Quantity;
            }

            var groupedList = reportViewModel.SoldProducts.GroupBy(x => GetFirstDayInMonth(x.SoldDate)).Select(x => new
            {
                Value = x.Sum(y => y.SoldPrice),
                Date = x.Key
            }).ToList();

            List<double[]> ChartData = new List<double[]>();

            foreach (var item in groupedList)
            {
                List<double> arr = new List<double>();
                arr.Add(item.Date.Subtract(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalMilliseconds);
                arr.Add(item.Value);
                ChartData.Add(arr.ToArray());
            }
            string json = JsonConvert.SerializeObject(ChartData);
            reportViewModel.ChartData = json;
            return View("_ShowReport", reportViewModel);
        }


        private DateTime GetFirstDayInMonth(DateTime dateTime)
        {
            return new DateTime(dateTime.Date.Year, dateTime.Date.Month, dateTime.Date.Day);
        }


    }
}

Smoczek Portal/webapp/Views/Shared/_Aside.cshtml
    <!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<aside id="left-panel">

    <!-- User info -->
    @{ Html.RenderPartial("_CurrentUser"); }
    <!-- end user info -->
    <!-- NAVIGATION : This navigation is also responsive

    To make this navigation dynamic please make sure to link the node
    (the reference to the nav > ul) after page load. Or the navigation
    will not initialize.
    -->
    <nav>
        <!-- NOTE: Notice the gaps after each icon usage <i></i>..
        Please note that these links work a bit different than
        traditional href="" links. See documentation for details.
        -->

        <ul>
            <li class="@Html.RouteIf("home", "active")">
                <a href="@Url.Action("index", "home")" title="Dashboard"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Główna</span></a>
            </li>

            <li class="@Html.RouteIf("reports", "active")">
                <a href="#"><i class="fa fa-lg fa-fw fa-bar-chart-o"></i> <span class="menu-item-parent">Raporty</span></a>
                <ul>
                    <li class="@Html.RouteIf("reports", "active")">
                        <a href="@Url.Action("Index", "Reports")">Pełna Lista Sprzedanych Produktów Komisantów</a>
                    </li>
                </ul>
            </li>

            <li class="@Html.RouteIf("brokers", "active") @Html.RouteIf("products", "active") @Html.RouteIf("messages", "active")">
                <a href="#"><i class="fa fa-lg fa-fw fa-tasks"></i> <span class="menu-item-parent">Komisanci</span></a>
                <ul>
                    <li class="@Html.RouteIf("brokers", "active")">
                        <a href="@Url.Action("brokers", "Broker")">Lista Komisantów</a>
                    </li>
                    <li class="@Html.RouteIf("messages", "active")">
                        <a href="@Url.Action("SmsMessages", "Messages")">Wsyłanie Sms</a>
                    </li>
                    <li class="@Html.RouteIf("showallproducts", "active")">
                        <a href="@Url.Action("ShowAllProducts", "Products")">Wyszukiwarka</a>
                    </li>
            
                </ul>
            </li>


            <li class="@Html.RouteIf("shopsettings", "active") @Html.RouteIf("CreateShopSettings", "active") @Html.RouteIf("ConfirmDeleteShopSettings", "active") @Html.RouteIf("EditShopSettings", "active") @Html.RouteIf("register", "active") @Html.RouteIf("appuserslist", "active") @Html.RouteIf("changeappuserrole", "active") @Html.RouteIf("removeappuserrole", "active") @Html.RouteIf("editappusers", "active") @Html.RouteIf("productcategorys", "active") @Html.RouteIf("createproductcategory", "active") @Html.RouteIf("editproductcategory", "active") @Html.RouteIf("confirmdeletebroker", "active")">
                <a href="#"><i class="fa fa-lg fa-fw fa-cogs"></i> <span class="menu-item-parent">Ustawienia</span></a>
                <ul>
                    <li class="@Html.RouteIf("shopsettings", "active") @Html.RouteIf("CreateShopSettings", "active") @Html.RouteIf("ConfirmDeleteShopSettings", "active") @Html.RouteIf("EditShopSettings", "active")">
                        <a href="@Url.Action("shopsettings", "settings")">Ustawienia Sklepu</a>
                    </li>
                    <li class="@Html.RouteIf("register", "active") @Html.RouteIf("appuserslist", "active") @Html.RouteIf("changeappuserrole", "active") @Html.RouteIf("removeappuserrole", "active") @Html.RouteIf("editappusers", "active")">
                        <a href="@Url.Action("appuserslist", "settings")">Lista Użytkowników Aplikacji</a>
                    </li>

                    <li class="@Html.RouteIf("productcategorys", "active") @Html.RouteIf("createproductcategory", "active") @Html.RouteIf("editproductcategory", "active") @Html.RouteIf("confirmdeletebroker", "active")">
                        <a href="@Url.Action("productcategorys", "settings")">Lista Kategorii Produktów</a>
                    </li>

                    
                </ul>
            </li>
        </ul>
     </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>

</aside>
<!-- END NAVIGATION -->

Smoczek Portal/webapp/Views/Shared/_CurrentUser.cshtml
<div class="login-info">
    <span>
        <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            <img src="~/content/img/avatars/sunny.png" alt="me" class="online" />
            <span>@User.Identity.Name.ToLower()</span>
            <i class="fa fa-angle-down"></i>
        </a>
    </span>
</div>

Smoczek Portal/webapp/Views/Shared/_Footer.cshtml
    <!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">Aplikacja komisowa 1.0 - Smoczek © 2015 </span>
        </div>
    </div>
</div>
<!-- END PAGE FOOTER -->

Smoczek Portal/webapp/Views/Shared/_Header.cshtml
    <!-- HEADER -->
<header id="header">
    <div id="logo-group">
      
        <!-- PLACE YOUR LOGO HERE -->
        @*<span id="logo"> <img src="~/content/img/logo.png" alt="Cloud Centre"> </span>*@
        <!-- END LOGO PLACEHOLDER -->
        @if (Request.IsAuthenticated)
        {
            <!-- Note: The activity badge color changes when clicked and resets the number to 0
            Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->

        <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
 
            <!-- END AJAX-DROPDOWN -->
        }
    </div>
    @if (Request.IsAuthenticated)
    {
    <!-- projects dropdown -->
      
    <!-- end projects dropdown -->
    }
    <section id="top-right">
        @if (@Model is HelperResult)
        {
            @Model
        }
        else
        {
            <div class="pull-right">
                @Html.Partial("_TopRight")
            </div>
        }
    </section>
</header>
<!-- END HEADER -->

Smoczek Portal/webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us" id="@ViewBag.PageId" class="@Settings.CurrentTheme">
<head>
    <meta charset=" utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title> Smoczek Portal </title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Basic Styles -->
    @Styles.Render("~/content/smartadmin")
    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/content/img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/content/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/content/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/content/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/iphone.png" media="screen and (max-device-width: 320px)">
</head>
<body class="menu-on-top">
    @*<body class="menu-on-top smart-style-3">*@
        @{ Html.RenderPartial("_Header", RenderSection("topright", false)); }
        @{ Html.RenderPartialIf("_Aside", Request.IsAuthenticated); }
        <div id="main" role="main">
            @{ Html.RenderPartialIf("_Ribbon", Request.IsAuthenticated); }
            @RenderBody()
        </div>
        @if (Request.IsAuthenticated)
        {
            Html.RenderPartial("_Footer");
            Html.RenderPartialIf("_Tiles", Settings.EnableTiles);
        }
        @{ Html.RenderPartial("_Scripts", RenderSection("pagespecific", false)); }
    </body>

</html>

Smoczek Portal/webapp/Views/Shared/_Ribbon.cshtml
<!-- RIBBON -->
<div id="ribbon">

    <span class="ribbon-button-alignment">
        <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
						<i class="fa fa-refresh"></i>
					</span>
    </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li>Home</li>
        <li>Dashboard</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
    <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
    <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
    <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
    </span> -->

</div>
<!-- END RIBBON -->

Smoczek Portal/webapp/Views/Shared/_Scripts.cshtml
<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script> if (!window.jQuery) { document.write('<script src="/scripts/libs/jquery-2.1.1.min.js"><\/script>'); } </script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script> if (!window.jQuery.ui) { document.write('<script src="/scripts/libs/jquery-ui-1.10.3.min.js"><\/script>'); } </script>

<!-- IMPORTANT: SmartAdmin Core -->
@Scripts.Render("~/scripts/smartadmin")

<!-- DataTables : plugin -->
@Scripts.Render("~/scripts/datatables")

<!-- jQGrid : plugin -->
@Scripts.Render("~/scripts/jq-grid")

<!-- Forms : plugin -->
@Scripts.Render("~/scripts/forms")

<!-- Flot Chart Plugin: Flot Engine, Flot Resizer, Flot Tooltip, Morris, Sparkline, EasyPie -->
@Scripts.Render("~/scripts/charts")
@Scripts.Render("~/bundles/jquery2")

<!-- DO NOT REMOVE : GLOBAL FUNCTIONS! -->
<script>
    $(document).ready(function () {
        pageSetUp();
        drawBreadCrumb();
    });
</script>

@if (@Model is HelperResult)
{
    @Model
}

Smoczek Portal/webapp/Views/Shared/_ShowMessage.cshtml
@if (TempData["message"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        <span class="sr-only">Wystąpił błąd: </span>
        @TempData["message"]
    </div>

}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        <span class="sr-only">Wystąpił błąd: </span>
        @TempData["Error"]
    </div>

}

Smoczek Portal/webapp/Views/Shared/_Tiles.cshtml
<!-- SHORTCUT AREA : With large tiles (activated via clicking user name tag)
Note: These tiles are completely responsive,
you can add as many as you like
-->
<div id="shortcut">
    <ul>
        <li>
            <a href="@Url.Action("inbox", "home")" class="jarvismetro-tile big-cubes bg-color-blue"> <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("calendar", "home")" class="jarvismetro-tile big-cubes bg-color-orangeDark"> <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("googlemap", "home")" class="jarvismetro-tile big-cubes bg-color-purple"> <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("invoice", "misc")" class="jarvismetro-tile big-cubes bg-color-blueDark"> <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("gallery", "appviews")" class="jarvismetro-tile big-cubes bg-color-greenLight"> <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("profile", "appviews")" class="jarvismetro-tile big-cubes selected bg-color-pinkDark"> <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span> </a>
        </li>
    </ul>
</div>
<!-- END SHORTCUT AREA -->

Smoczek Portal/webapp/Views/Shared/_TopRight.cshtml
<!-- collapse menu button -->
<div id="hide-menu" class="btn-header pull-right">

    <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
</div>

<div class="pull-left text-right">

    <div class="top-right-username">
        @Html.CurrentUserHelper()
    </div>
</div>

<!-- Note: The activity badge color changes when clicked and resets the number to 0
Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
<!-- end collapse menu -->
<!-- #MOBILE -->
<!-- Top menu profile link : this shows only when top menu is active -->
<ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
    <li class="">
        <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
            <img src="~/content/img/avatars/AvatarSmall.png" alt="" class="online" />
        </a>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="@Url.Action("Logout", "Account")" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-lg fa-fw fa-power-off"></i> Logout</a>
            </li>
        </ul>
    </li>
</ul>





<script type="text/javascript">

   

</script>