Smoczek Portal/webapp/Models/ViewModels/BrokerViewModel.cs
using CloudCentre.Filters;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CloudCentre.Models.ViewModels
{
    public class BrokerViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Pole imie jest wymagane")]
        [Display(Name = "Imię")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Pole nazwisko jest wymagane")]
        [Display(Name = "Nazwisko")]

        public string LastName { get; set; }

        [Required(ErrorMessage = "Pole dowód osobisty jest wymagane")]
        [Display(Name = "Dowód Osobisty")]

        public string Card { get; set; }

        [Required(ErrorMessage = "Pole adres jest wymagane")]
        [Display(Name = "Adres")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Pole numer umowy jest wymagane")]
        [Range(1, int.MaxValue, ErrorMessage = "Numer umowy musi byc wiekszy niz 0")]
        [Display(Name = "Numer Umowy")]
        public int Contract { get; set; }

        [EmailAddress]
        [Display(Name = "E-mail")]
        //[Required(ErrorMessage = "Pole jest wymagane")]
        public string Email { get; set; }

        [DataType(DataType.PhoneNumber, ErrorMessage = "Pole musi być numeryczne")]
        [Required(ErrorMessage = "Pole jest wymagane")]
        [Display(Name = "Numer Telefonu")]
        public int? Phone { get; set; }


        public string FullName
        {
            get { return string.Join(" ", FirstName, LastName); }
          
        }

       

    }
}

Smoczek Portal/webapp/Controllers/BrokerController.cs
using AutoMapper;
using CloudCentre.DAL.Models;
using CloudCentre.Filters;
using CloudCentre.Models.ViewModels;
using CloudCentre.Services.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CloudCentre.Controllers
{
    [CurrentUserActionFilter]
    public class BrokerController : BaseController
    {
        private readonly IBrokerService _brokerService;
        public BrokerController(IBrokerService brokerService)
        {
            this._brokerService = brokerService;
        }

        [HttpGet]
        public ActionResult Brokers()
        {
            List<BrokerViewModel> viewModel = Mapper.Map<List<BrokerViewModel>>(_brokerService.GetBrokers());
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult CreateBroker()
        {
           BrokerViewModel viewModel = new BrokerViewModel() { Contract = _brokerService.RetriveLastContranctNumber() };
           return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBroker(BrokerViewModel viewModel)
        {
            if (!ModelState.IsValid) {
                return View(viewModel);
            }

            if (_brokerService.CheckIfContractNumberisTaken(viewModel.Contract))
            {
                ModelState.AddModelError("", "Ten numer umowy jest już zajety");
                return View(viewModel);
            }


            Broker broker = Mapper.Map<Broker>(viewModel);
            bool result = _brokerService.CreateBroker(broker);

            if (!result)
            {
                ModelState.AddModelError("", "Wystąpił błąd przy dodawaniu komisanta - sprawdż logi");
                return View(viewModel);
            }
            TempData["message"] = "Dodano komisanta";
            return RedirectToAction("Brokers");
        }


        [HttpGet]
        public ActionResult EditBroker(int Id)
        {
            if (Id == 0)
            {
                return RedirectToAction("Brokers");
            }

            Broker broker = _brokerService.GetBroker(Id);
            if (broker == null)
            {
                TempData["Error"] = "Nie ma takiego komisanta";
                return RedirectToAction("Brokers");
            }

            BrokerViewModel viewModel = Mapper.Map<BrokerViewModel>(broker);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBroker(BrokerViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            Broker broker = _brokerService.GetBroker(viewModel.ID);

            if(broker == null)
            {
                TempData["Error"] = "Nie ma takiego komisanta";
                return RedirectToAction("Brokers");
            }

            if (_brokerService.CheckIfContractNumberisTaken(viewModel.Contract))
            {
                if (broker.ID != viewModel.ID)
                {
                    ModelState.AddModelError("", "Ten numer umowy jest już zajety");
                    return View(viewModel);
                }
            }


            Mapper.Map(viewModel, broker);

            bool result = _brokerService.EditBroker(broker);

            if (!result)
            {
                ModelState.AddModelError("", "Wystąpił błąd przy edytowaniu komisanta - sprawdż logi");
                return View(viewModel);
            }
            TempData["message"] = "Dane Komisanta zstały zdytowane pomyślnie";
            return RedirectToAction("Brokers");
        }

        [HttpGet]
        public ActionResult ConfirmDeleteBroker(int Id)
        {
            Broker broker = _brokerService.GetBroker(Id);
            if (broker == null)
            {
                TempData["Error"] = "Nie ma takiego komisanta";
                return RedirectToAction("Brokers");
            }

            BrokerViewModel viewModel = Mapper.Map<BrokerViewModel>(broker);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmDeleteBroker(BrokerViewModel viewModel)
        {
            Broker broker = _brokerService.GetBroker(viewModel.ID);

            if (broker == null)
            {
                TempData["Error"] = "Nie ma takiego komisanta";
                return RedirectToAction("Brokers");
            }

            bool result = _brokerService.DeleteBroker(broker);

            if (!result)
            {
                ModelState.Clear();
                ModelState.AddModelError("", "Wystąpił błąd przy usuwaniu komisanta - sprawdż logi");
                return View(viewModel);
            }
            TempData["message"] = "Komisant został usuniety pomyślnie";
            return RedirectToAction("Brokers");
        }

       
    }
}

Smoczek Portal/webapp/Views/Broker/ConfirmDeleteBroker.cshtml
@model CloudCentre.Models.ViewModels.BrokerViewModel

<div class="container">
    <div id="content" class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
                <div class="well no-padding">
                    <form action="@Url.Action("ConfirmDeleteBroker", "Broker")" method="POST" id="smart-form-register" class="smart-form client-form">
                        <header>
                            Czy napewno czcesz usunąc tego komisanta
                        </header>
                        @Html.HiddenFor(x => x.ID)
                        @Html.AntiForgeryToken()
                        @Html.ValidationBootstrap()

                        <fieldset>
                            <div class="row">
                                <section class="col col-4">
                                    <label class="input">
                                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.DisplayFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Imię", @autocomplete = "off" } })
                                        <b class="tooltip tooltip-bottom-right">Imię</b>
                                    </label>
                                </section>
                                <section class="col col-4">
                                    <label class="input">
                                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.DisplayFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nazwisko" } })
                                        <b class="tooltip tooltip-bottom-right">Nazwisko</b>
                                    </label>
                                </section>
                            </div>
                        </fieldset>
                        <footer>

                            <button type="submit" class="btn bg-primary">
                                Usuń komisanta
                            </button>
                            @Html.ActionLink("Powrót do listy komisantów", "Brokers", "Broker", null, new { @class = "btn bg-primary" })
                        </footer>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Smoczek Portal/webapp/Views/Broker/CreateBroker.cshtml
@model CloudCentre.Models.ViewModels.BrokerViewModel

<div class="container">
    <div id="content" class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
                <div class="well no-padding">

                    <form action="@Url.Action("CreateBroker", "Broker")" method="POST" id="smart-form-register" class="smart-form client-form">
                        <header>
                            Formularz Wprowadzania nowego komisanta
                        </header>
                        @Html.AntiForgeryToken()
                        @Html.ValidationBootstrap()
                        <fieldset>
                            <div class="row">
                                <section class="col col-6">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Contract, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Contract, new { htmlAttributes = new { @class = "form-control", @placeholder = "Numer Umowy" } })
                                        @Html.ValidationMessageFor(model => model.Contract)


                                        <b class="tooltip tooltip-bottom-right"> Numer umowy komisanta</b>
                                    </label>
                                </section>
                                <section class="col col-6">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Card, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Card, new { htmlAttributes = new { @class = "form-control", @placeholder = "Numer Dowodu osobistego" } })
                                        @Html.ValidationMessageFor(model => model.Card)
                                        <b class="tooltip tooltip-bottom-right"> Numer dowodu osobistego komisanta</b>
                                    </label>
                                </section>
                            </div>
                        </fieldset>
                        <fieldset>
                            <div class="row">
                                <section class="col col-4">
                                    <label class="input">
                                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Imię", @autocomplete = "off" } })
                                        <b class="tooltip tooltip-bottom-right">Imię</b>
                                        @Html.ValidationMessageFor(model => model.FirstName)
                                    </label>
                                </section>
                                <section class="col col-4">
                                    <label class="input">
                                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nazwisko" } })
                                        <b class="tooltip tooltip-bottom-right">Nazwisko</b>
                                        @Html.ValidationMessageFor(model => model.LastName)
                                    </label>
                                </section>
                                <section class="col col-4">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Adres zamieszkania" } })
                                        <b class="tooltip tooltip-bottom-right">Adress Zamieszkania</b>
                                        @Html.ValidationMessageFor(model => model.Address)
                                    </label>
                                </section>
                            </div>
                        </fieldset>

                        <fieldset>
                            <div class="row">
                                <section class="col col-6">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Telefon", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(model => model.Phone)
                                        <b class="tooltip tooltip-bottom-right">Numer Telefonu</b>
                                    </label>
                                </section>
                                <section class="col col-6">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "E-mail" } })
                                        @Html.ValidationMessageFor(model => model.Email)
                                        <b class="tooltip tooltip-bottom-right">Email</b>
                                    </label>
                                </section>
                            </div>
                        </fieldset>

                        <footer>

                            <button type="submit" class="btn bg-primary">
                                Zapisz komisanta
                            </button>
                            @Html.ActionLink("Powrót do listy komisantów", "Brokers", "Broker", null, new { @class = "btn bg-primary" })
                        </footer>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


    <script type="text/javascript">

    </script>

Smoczek Portal/webapp/Views/Broker/EditBroker.cshtml
@model CloudCentre.Models.ViewModels.BrokerViewModel

<div class="container">
    <div id="content" class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
                <div class="well no-padding">
                    <form action="@Url.Action("EditBroker", "Broker")" method="POST" id="smart-form-register" class="smart-form client-form">
                        <header>
                            Formularz edycji komisanta
                        </header>
                        @Html.HiddenFor(x => x.ID)
                        @Html.AntiForgeryToken()
                        @Html.ValidationBootstrap()
                        <fieldset>
                            <div class="row">
                                <section class="col col-6">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Contract, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Contract, new { htmlAttributes = new { @class = "form-control", @placeholder = "Numer Umowy", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(model => model.Contract)
                                        <b class="tooltip tooltip-bottom-right"> Numer umowy komisanta</b>
                                    </label>
                                </section>
                                <section class="col col-6">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Card, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Card, new { htmlAttributes = new { @class = "form-control", @placeholder = "Numer Dowodu osobistego" } })
                                        @Html.ValidationMessageFor(model => model.Card)
                                        <b class="tooltip tooltip-bottom-right"> Numer dowodu osobistego komisanta</b>
                                    </label>
                                </section>
                            </div>
                        </fieldset>
                        <fieldset>
                            <div class="row">
                                <section class="col col-4">
                                    <label class="input">
                                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Imię", @autocomplete = "off" } })
                                        <b class="tooltip tooltip-bottom-right">Imię</b>
                                        @Html.ValidationMessageFor(model => model.FirstName)
                                    </label>
                                </section>
                                <section class="col col-4">
                                    <label class="input">
                                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nazwisko" } })
                                        <b class="tooltip tooltip-bottom-right">Nazwisko</b>
                                        @Html.ValidationMessageFor(model => model.LastName)
                                    </label>
                                </section>
                                <section class="col col-4">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Adres zamieszkania" } })
                                        <b class="tooltip tooltip-bottom-right">Adress Zamieszkania</b>
                                    </label>
                                </section>
                            </div>
                        </fieldset>

                        <fieldset>
                            <div class="row">
                                <section class="col col-6">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Telefon", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(model => model.Phone)
                                        <b class="tooltip tooltip-bottom-right">Numer Telefonu</b>
                                    </label>
                                </section>
                                <section class="col col-6">
                                    <label class="input">
                                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-12" })
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "E-mail" } })
                                        @Html.ValidationMessageFor(model => model.Email)
                                        <b class="tooltip tooltip-bottom-right">Email</b>
                                    </label>
                                </section>
                            </div>
                        </fieldset>
                        <footer>

                            <button type="submit" class="btn bg-primary">
                                Edutuj komisanta
                            </button>
                            @Html.ActionLink("Powrót do listy komisantów", "Brokers", "Broker", null, new { @class = "btn bg-primary" })
                        </footer>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>