Smoczek Portal/webapp/Models/ViewModels/ProductCategoryViewModel.cs
using CloudCentre.Filters;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CloudCentre.Models.ViewModels
{
    public class ProductCategoryViewModel
    {
        public int ID { get; set; }

        [Required]
        [Display(Name="Nazwa Kategorii")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Numeracja początkowa")]
        [Range(1, int.MaxValue , ErrorMessage = "Numer musi byc wiekszy niz 0")]
        public int StartNumber { get; set; }


        [Required]
        [Display(Name = "Numeracja koncowa")]
        [Range(1, int.MaxValue, ErrorMessage = "Numer musi byc wiekszy niz 0")]
        public int EndNumber { get; set; }

    }
}

Smoczek Portal/webapp/Controllers/SettingsController.cs
#region Using

using AutoMapper;
using CloudCentre.Controllers;
using CloudCentre.DAL.Models;
using CloudCentre.DAL.ViewModels;
using CloudCentre.Filters;
using CloudCentre.Models.ViewModels;
using CloudCentre.Services.Abstract;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

#endregion

namespace CloudCentrePortal.Controllers
{
    [Authorize(Roles = Roles.Admin)]
    [CurrentUserActionFilter]
    [RolesActionFilter]
    public class SettingsController : BaseController
    {
        private readonly IStoreSettingsService _storeSettingsService;
        private readonly IUserManagerService _userManagerService;
        private readonly IProductCategoryService _productCategoryService;


        public SettingsController(IStoreSettingsService storeSettingsService, IUserManagerService userManagerService, IProductCategoryService productCategoryService)
        {
            this._storeSettingsService = storeSettingsService;
            this._userManagerService = userManagerService;
            this._productCategoryService = productCategoryService;
        }

        [HttpGet]
        public ActionResult ShopSettings()
        {
            StoreSettingsViewModel viewModel = Mapper.Map<StoreSettingsViewModel>(_storeSettingsService.GetStoreSettings());
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult CreateShopSettings()
        {
            return View(new StoreSettingsViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateShopSettings(StoreSettingsViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            StoreSettings storeSettings = Mapper.Map<StoreSettings>(viewModel);
            bool result = _storeSettingsService.CreateStoreSettings(storeSettings);

            if (!result)
            {
                ModelState.AddModelError("", "Wystąpił błąd przy dodawaniu ustawień - sprawdż logi");
                return View(viewModel);
            }
            TempData["message"] = "Dodano ustawienia sklepu";
            return RedirectToAction("ShopSettings");
        }

        [HttpGet]
        public ActionResult EditShopSettings(int Id)
        {
            if (Id == 0) {
                return RedirectToAction("ShopSettings");
            }

            StoreSettings storeSettings = _storeSettingsService.GetStoreSettings(Id);
            if(storeSettings == null)
            {
                TempData["Error"] = "Nie ma takich ustawień";
                return RedirectToAction("ShopSettings");
            }

            StoreSettingsViewModel viewModel = Mapper.Map<StoreSettingsViewModel>(storeSettings);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditShopSettings(StoreSettingsViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            StoreSettings storeSettings = Mapper.Map<StoreSettings>(viewModel);
            bool result = _storeSettingsService.EditStoreSettings(storeSettings);

            if (!result)
            {
                ModelState.AddModelError("", "Wystąpił błąd przy edytowaniu ustawień - sprawdż logi");
                return View(viewModel);
            }
            TempData["message"] = "Ustawienia sklepu zostały edytowane pomyślnie";
            return RedirectToAction("ShopSettings");
        }

        [HttpGet]
        public ActionResult ConfirmDeleteShopSettings(int Id)
        {
            StoreSettings storeSettings = _storeSettingsService.GetStoreSettings(Id);
            if (storeSettings == null)
            {
                TempData["Error"] = "Nie ma takich ustawień";
                return RedirectToAction("ShopSettings");
            }

            StoreSettingsViewModel viewModel = Mapper.Map<StoreSettingsViewModel>(storeSettings);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmDeleteShopSettings(StoreSettingsViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            StoreSettings storeSettings = _storeSettingsService.GetStoreSettings(viewModel.ID);

            if(storeSettings == null)
            {
                TempData["Error"] = "Nie ma takich ustawień";
                return RedirectToAction("ShopSettings");
            }
         
            bool result = _storeSettingsService.DeleteStoreSettings(storeSettings);

            if (!result)
            {
                ModelState.AddModelError("", "Wystąpił błąd przy usuwaniu ustawień - sprawdż logi");
                return View(viewModel);
            }
            TempData["message"] = "Ustawienia sklepu zostały usunięte pomyślnie";
            return RedirectToAction("ShopSettings");
        }


        [HttpGet]
        public ActionResult AppUsersList()
        {
            List<AppIdentityUserViewModel> viewModelList = Mapper.Map<List<AppIdentityUserViewModel>>(_userManagerService.GetAllUsers());
            return View(viewModelList);
        }


        [HttpGet]
        public async Task<ActionResult> ChangeAppUserRole(string Id)
        {
            if (Id == null)
            {
                return RedirectToAction("ShopSettings");
            }
            AppIdentityUser appIdentityUser = await _userManagerService.GetUserById(Id);

            if(appIdentityUser == null)
            {
                TempData["Error"] = "Nie ma takiego użytkownika";
                return RedirectToAction("AppUsersList");
            }

            AppIdentityUserViewModel viewModel = Mapper.Map<AppIdentityUserViewModel>(appIdentityUser);
            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> ChangeAppUserRole(AppIdentityUserViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            AppIdentityUser appIdentityUser = await _userManagerService.GetUserById(viewModel.Id);

            if(appIdentityUser == null)
            {
                TempData["Error"] = "Nie ma takiego użytkownika";
                return RedirectToAction("AppUsersList");
            }

            string role = _userManagerService.GetUserRole(appIdentityUser.Id).FirstOrDefault();
            string roleToChange = _userManagerService.GetRole(viewModel.RoleId).Name;

            if (role == null || roleToChange == null)
            {
                TempData["Error"] = "Użytkownik nie ma przypisanej roli";
                return RedirectToAction("AppUsersList");
            }

            IdentityResult removeFromRoleResult =  await _userManagerService.RemoveUserFromRoleAsync(appIdentityUser, role);
            IdentityResult addToRoleResult = await _userManagerService.AddUserToRoleAsync(appIdentityUser, roleToChange);

            TempData["message"] = "Rola została pomyslnie zmieniona dla uzytkownika";
            return RedirectToAction("AppUsersList");
        }


        [HttpGet]
        public async Task<ActionResult> RemoveAppUserRole(string Id)
        {
            if (Id == null)
            {
                return RedirectToAction("ShopSettings");
            }
            AppIdentityUser appIdentityUser = await _userManagerService.GetUserById(Id);

            if (appIdentityUser == null)
            {
                TempData["Error"] = "Nie ma takiego użytkownika";
                return RedirectToAction("AppUsersList");
            }

            AppIdentityUserViewModel viewModel = Mapper.Map<AppIdentityUserViewModel>(appIdentityUser);
            return View(viewModel);
        }


        [HttpPost]
        public async Task<ActionResult> RemoveAppUserRole(AppIdentityUserViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            AppIdentityUser appIdentityUser = await _userManagerService.GetUserById(viewModel.Id);

            if (appIdentityUser == null)
            {
                TempData["Error"] = "Nie ma takiego użytkownika";
                return RedirectToAction("AppUsersList");
            }

            IdentityResult removeUser = await _userManagerService.RemoveUserData(appIdentityUser);

            if (!removeUser.Succeeded)
            {
                TempData["Error"] = "Wystapił błąd podczas usuwania uzytkownika";
                return RedirectToAction("AppUsersList");
            }

            TempData["message"] = "Użytkownik został usuniety poprawnie";
            return RedirectToAction("AppUsersList");
        }

        [HttpGet]
        public async Task<ActionResult> EditAppUsers(string Id)
        {
            if (Id == null)
            {
                return RedirectToAction("ShopSettings");
            }

            AppIdentityUser appIdentityUser = await _userManagerService.GetUserById(Id);

            if (appIdentityUser == null)
            {
                TempData["Error"] = "Nie ma takiego użytkownika";
                return RedirectToAction("AppUsersList");
            }

            IdentityUserEditViewModel viewModel = Mapper.Map<IdentityUserEditViewModel>(appIdentityUser);
            return View(viewModel);
        }


        [HttpPost]
        public async Task<ActionResult> EditAppUsers(IdentityUserEditViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            AppIdentityUser appIdentityUser = await _userManagerService.GetUserById(viewModel.Id);

         

            if (appIdentityUser == null)
            {
                TempData["Error"] = "Nie ma takiego użytkownika";
                return RedirectToAction("AppUsersList");
            }

            string OrgEmail = appIdentityUser.Email;

            Mapper.Map(viewModel, appIdentityUser);

Smoczek Portal/webapp/Views/Settings/ChangeAppUserRole.cshtml
@model CloudCentre.DAL.ViewModels.AppIdentityUserViewModel
<div id="content" class="container text-center">
    <div class="well well-light col-md-12">
        @using (Html.BeginForm("ChangeAppUserRole", "Settings", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.Id)
           
            <div class="form-group row col-md-12">
                <div class="col-md-4">
                </div>
              
                <div class="col-md-4">
                    @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-12" })
                    @Html.DropDownListFor(model => model.RoleId, (IEnumerable<SelectListItem>)ViewBag.AppRoles, "Wybierz nową rolę", new { @class = "form-control" })
                </div>
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
                <div class="col-md-4">
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-4">
                </div>
                    <div class="col-md-4">
                        @Html.ActionLink("Powrót do listy użytkowników", "AppUsersList", null, new { @class = "btn bg-primary" })
                        <button type="submit" class="btn bg-primary">Zmień rolę</button>
                    </div>
                </div>
        }
    </div>
</div>

Smoczek Portal/webapp/Views/Settings/ConfirmDeleteProductCategory.cshtml
@model CloudCentre.Models.ViewModels.ProductCategoryViewModel


<div id="content" class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
            <div class="well no-padding">
                <form action="@Url.Action("ConfirmDeleteProductCategory", "Settings")" method="POST" id="smart-form-register" class="smart-form client-form">
                    <header>
                        Czy napewno czcesz usunąc tą kategorię
                    </header>
                    @Html.HiddenFor(x => x.ID)
                    @Html.AntiForgeryToken()
                    @Html.ValidationBootstrap()

                    <fieldset>
                        <div class="row">
                            <section class="col col-12">
                                <label class="input">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-12" })
                                    @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nazwa kategori" } })
                                    <b class="tooltip tooltip-bottom-right"> Nazwa kategori produktu</b>
                                </label>
                            </section>
                        </div>
                    </fieldset>
                    <footer>

                        <button type="submit" class="btn bg-primary">
                            Usuń Kategorię
                        </button>
                        @Html.ActionLink("Powrót do listy kategorii", "ProductCategorys", "Settings", null, new { @class = "btn bg-primary" })
                    </footer>

                </form>
            </div>
        </div>
    </div>
</div>

Smoczek Portal/webapp/Views/Settings/ConfirmDeleteShopSettings.cshtml
@model CloudCentre.DAL.ViewModels.StoreSettingsViewModel



<!-- MAIN CONTENT -->
<div id="content">
    <!-- row -->
    <div class="row">
        <!-- col -->
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <!-- PAGE HEADER -->
                <i class="fa fa-fw fa-sitemap"></i>
                Usuń Ustawienia Sklepu
            </h1>
        </div>

        <div class="col-sm-12">
            <div class="well well-light">
                <!-- widget grid -->
                <section id="widget-grid" class="">
                    <!-- row -->
                    <div class="row">
                        <!-- SINGLE GRID -->
                        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="row">
                                <!-- NEW WIDGET START -->
                                <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                                    <br />
                                    <br />
                                    @using (Html.BeginForm("ConfirmDeleteShopSettings", "Settings", FormMethod.Post))
                                    {
                                        @Html.HiddenFor(model => model.ID)
                                        @Html.HiddenFor(model => model.Name)
                                        @Html.HiddenFor(model => model.Address)
                                        @Html.AntiForgeryToken()
                                        <div class="container col-md-8">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Name)
                                                @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })

                                            </div>

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Address)
                                                @Html.DisplayFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })

                                            </div>

                                            <div class="form-group">

                                                @Html.ActionLink("Powrót do ustawień sklepu", "ShopSettings", null, new { @class = "btn bg-primary" })
                                                <button type="submit" class="btn bg-primary">Usuń</button>
                                            </div>
                                        </div>
                                    }
                                </article>
                                <!-- WIDGET END -->
                            </div>
                        </article><!-- GRID END -->
                    </div><!-- end row -->
                </section>
                <!-- end widget grid -->
            </div>
        </div>
    </div>
</div>


<!-- END MAIN CONTENT -->
@section pagespecific {
    <script src="~/Scripts/app.modals.js"></script>
    <script type="text/javascript">

                // DO NOT REMOVE : GLOBAL FUNCTIONS!

                $(document).ready(function () {

                    /* // DOM Position key index //

                    l - Length changing (dropdown)
                    f - Filtering input (search)
                    t - The Table! (datatable)
                    i - Information (records)
                    p - Pagination (paging)
                    r - pRocessing
                    < and > - div elements
                    <"#id" and > - div with an id
                    <"class" and > - div with a class
                    <"#id.class" and > - div with an id and class

                    Also see: http://legacy.datatables.net/usage/features
                    */

                    /* BASIC ;*/
                    var responsiveHelper_dt_basic = undefined;
                    var responsiveHelper_datatable_fixed_column = undefined;
                    var responsiveHelper_datatable_col_reorder = undefined;
                    var responsiveHelper_datatable_tabletools = undefined;

                    var breakpointDefinition = {
                        tablet: 1024,
                        phone: 480
                    };

                    $('#dt_basic').dataTable({
                        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                            "t" +
                            "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                        "autoWidth": true,
                        "preDrawCallback": function () {
                            // Initialize the responsive datatables helper once.
                            if (!responsiveHelper_dt_basic) {
                                responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
                            }
                        },
                        "rowCallback": function (nRow) {
                            responsiveHelper_dt_basic.createExpandIcon(nRow);
                        },
                        "drawCallback": function (oSettings) {
                            responsiveHelper_dt_basic.respond();
                        }
                    });

                    /* END BASIC */

                    /* COLUMN FILTER  */
                    var otable = $('#datatable_fixed_column').DataTable({
                        //"bFilter": false,
                        //"bInfo": false,
                        //"bLengthChange": false
                        //"bAutoWidth": false,
                        //"bPaginate": false,
                        //"bStateSave": true // saves sort state using localStorage
                        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>" +
                                "t" +
                                "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                        "autoWidth": true,
                        "preDrawCallback": function () {
                            // Initialize the responsive datatables helper once.
                            if (!responsiveHelper_datatable_fixed_column) {
                                responsiveHelper_datatable_fixed_column = new ResponsiveDatatablesHelper($('#datatable_fixed_column'), breakpointDefinition);
                            }
                        },
                        "rowCallback": function (nRow) {
                            responsiveHelper_datatable_fixed_column.createExpandIcon(nRow);
                        },
                        "drawCallback": function (oSettings) {
                            responsiveHelper_datatable_fixed_column.respond();
                        }

                    });

                    // custom toolbar
                    $("div.toolbar").html('<div class="text-right"><img src="/Content/img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');

                    // Apply the filter
                    $("#datatable_fixed_column thead th input[type=text]").on('keyup change', function () {

                        otable
                            .column($(this).parent().index() + ':visible')
                            .search(this.value)
                            .draw();

                    });
                    /* END COLUMN FILTER */

                    /* COLUMN SHOW - HIDE */
                    $('#datatable_col_reorder').dataTable({
                        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'C>r>" +
                                "t" +
                                "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                        "autoWidth": true,
                        "preDrawCallback": function () {
                            // Initialize the responsive datatables helper once.
                            if (!responsiveHelper_datatable_col_reorder) {
                                responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
                            }
                        },
                        "rowCallback": function (nRow) {
                            responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
                        },
                        "drawCallback": function (oSettings) {
                            responsiveHelper_datatable_col_reorder.respond();
                        }
                    });

                    /* END COLUMN SHOW - HIDE */

                    /* TABLETOOLS */
                    $('#datatable_tabletools').dataTable({

                        // Tabletools options:
                        //   https://datatables.net/extensions/tabletools/button_options
                        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
                                "t" +
                                "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                        "oTableTools": {
                            "aButtons": [
                            "copy",
                            "csv",
                            "xls",
                               {
                                   "sExtends": "pdf",
                                   "sTitle": "SmartAdmin_PDF",
                                   "sPdfMessage": "SmartAdmin PDF Export",
                                   "sPdfSize": "letter"
                               },
                               {
                                   "sExtends": "print",
                                   "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
                               }
                            ],
                            "sSwfPath": "/Scripts/plugin/datatables/swf/copy_csv_xls_pdf.swf"
                        },
                        "autoWidth": true,
                        "preDrawCallback": function () {
                            // Initialize the responsive datatables helper once.
                            if (!responsiveHelper_datatable_tabletools) {
                                responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
                            }
                        },
                        "rowCallback": function (nRow) {
                            responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
                        },
                        "drawCallback": function (oSettings) {
                            responsiveHelper_datatable_tabletools.respond();
                        }
                    });

                    /* END TABLETOOLS */
                })

    </script>
}

Smoczek Portal/webapp/Views/Settings/CreateProductCategory.cshtml
@model CloudCentre.Models.ViewModels.ProductCategoryViewModel


<div id="content" class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
            <div class="well no-padding">

                <form action="@Url.Action("CreateProductCategory", "Settings")" method="POST" id="smart-form-register" class="smart-form client-form">
                    <header>
                        Formularz Wprowadzania nowej kategori
                    </header>
                    @Html.AntiForgeryToken()
                    @Html.ValidationBootstrap()
                    <fieldset>
                        <div class="row">
                            <section class="col col-12">
                                <label class="input">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-12" })
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nazwa kategori" } })
                                    <b class="tooltip tooltip-bottom-right"> Nazwa kategori produktu</b>
                                </label>
                            </section>
                        </div>
                    </fieldset>
                    <fieldset>
                        <div class="row">
                            <section class="col col-6">
                                <label class="input">
                                    @Html.LabelFor(model => model.StartNumber, htmlAttributes: new { @class = "control-label col-md-12" })
                                    @Html.EditorFor(model => model.StartNumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "Początek numeracji" } })
                                    @Html.ValidationMessageFor(model => model.StartNumber)
                                    <b class="tooltip tooltip-bottom-right">Imię</b>
                                </label>
                            </section>
                            <section class="col col-6">
                                <label class="input">
                                    @Html.LabelFor(model => model.EndNumber, htmlAttributes: new { @class = "control-label col-md-12" })
                                    @Html.EditorFor(model => model.EndNumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "Koniec numeracji" } })
                                    @Html.ValidationMessageFor(model => model.EndNumber)
                                    <b class="tooltip tooltip-bottom-right">Nazwisko</b>
                                </label>
                            </section>
                            
                        </div>
                    </fieldset>
                    <footer>

                        <button type="submit" class="btn bg-primary">
                            Zapisz Kategorię
                        </button>
                        @Html.ActionLink("Powrót do listy kategori", "ProductCategorys", "Settings", null, new { @class = "btn bg-primary" })
                    </footer>

                </form>
            </div>
        </div>
    </div>
</div>

Smoczek Portal/webapp/Views/Settings/RemoveAppUserRole.cshtml
@model CloudCentre.DAL.ViewModels.AppIdentityUserViewModel
<div id="content" class="container text-center">
    <div class="well well-light col-md-12">
        @using (Html.BeginForm("RemoveAppUserRole", "Settings", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.Id)

            <h3>Czy napewno usunąć tego użytkownika?</h3>

            <div class="form-group row">
                <div class="col-md-4">
                </div>
                    <div class="col-md-4">
                        @Html.ActionLink("Powrót do listy użytkowników", "AppUsersList", null, new { @class = "btn bg-primary" })
                        <button type="submit" class="btn bg-primary">Usuń użytkownika</button>
                    </div>
            </div>
        }
    </div>
</div>